export const authVariablesLight = {
  colors: {
    brand: '#0f766e',
    brandAccent: '#0d6560',
    brandButtonText: '#ffffff',
    inputBackground: '#ffffff',
    inputBorder: '#e7e5e4',
    inputBorderHover: '#d6d3d1',
    inputBorderFocus: '#0f766e',
    inputText: '#1c1917',
    inputLabelText: '#1c1917',
    inputPlaceholder: '#78716c',
    defaultButtonBackground: '#f5f5f4',
    defaultButtonBackgroundHover: '#e7e5e4',
    defaultButtonBorder: '#e7e5e4',
    defaultButtonText: '#1c1917',
    anchorTextColor: '#0f766e',
    anchorTextHoverColor: '#0d6560',
    dividerBackground: '#e7e5e4',
    messageText: '#1c1917',
    messageTextDanger: '#dc2626',
  },
  fonts: {
    bodyFontFamily: 'var(--font-body), DM Sans, sans-serif',
    buttonFontFamily: 'var(--font-body), DM Sans, sans-serif',
    inputFontFamily: 'var(--font-body), DM Sans, sans-serif',
    labelFontFamily: 'var(--font-body), DM Sans, sans-serif',
  },
  fontSizes: {
    baseInputSize: '14px',
    baseLabelSize: '14px',
    baseBodySize: '14px',
    baseButtonSize: '14px',
  },
  borderWidths: {
    buttonBorderWidth: '1px',
    inputBorderWidth: '1px',
  },
  radii: {
    borderRadiusButton: '0.625rem',
    buttonBorderRadius: '0.625rem',
    inputBorderRadius: '0.625rem',
  },
  space: {
    inputPadding: '0.625rem 0.75rem',
    buttonPadding: '0.625rem 1rem',
  },
}

export const authVariablesDark = {
  colors: {
    brand: '#2dd4bf',
    brandAccent: '#5eead4',
    brandButtonText: '#042f2e',
    inputBackground: '#1c1c1a',
    inputBorder: '#2e2e2b',
    inputBorderHover: '#3e3e3b',
    inputBorderFocus: '#2dd4bf',
    inputText: '#fafaf9',
    inputLabelText: '#e7e5e4',
    inputPlaceholder: '#a8a29e',
    defaultButtonBackground: '#1c1c1a',
    defaultButtonBackgroundHover: '#262624',
    defaultButtonBorder: '#2e2e2b',
    defaultButtonText: '#e7e5e4',
    anchorTextColor: '#5eead4',
    anchorTextHoverColor: '#2dd4bf',
    dividerBackground: '#2e2e2b',
    messageText: '#fafaf9',
    messageTextDanger: '#f87171',
  },
  fonts: {
    bodyFontFamily: 'var(--font-body), DM Sans, sans-serif',
    buttonFontFamily: 'var(--font-body), DM Sans, sans-serif',
    inputFontFamily: 'var(--font-body), DM Sans, sans-serif',
    labelFontFamily: 'var(--font-body), DM Sans, sans-serif',
  },
  fontSizes: {
    baseInputSize: '14px',
    baseLabelSize: '14px',
    baseBodySize: '14px',
    baseButtonSize: '14px',
  },
  borderWidths: {
    buttonBorderWidth: '1px',
    inputBorderWidth: '1px',
  },
  radii: {
    borderRadiusButton: '0.625rem',
    buttonBorderRadius: '0.625rem',
    inputBorderRadius: '0.625rem',
  },
  space: {
    inputPadding: '0.625rem 0.75rem',
    buttonPadding: '0.625rem 1rem',
  },
}
