export const authVariablesLight = {
  colors: {
    brand: '#334155',
    brandAccent: '#1e293b',
    brandButtonText: '#ffffff',
    inputBackground: '#ffffff',
    inputBorder: '#e2e8f0',
    inputBorderHover: '#cbd5e1',
    inputBorderFocus: '#334155',
    inputText: '#0a0a0a',
    inputLabelText: '#0a0a0a',
    inputPlaceholder: '#64748b',
    defaultButtonBackground: '#f1f5f9',
    defaultButtonBackgroundHover: '#e2e8f0',
    defaultButtonBorder: '#e2e8f0',
    defaultButtonText: '#0f172a',
    anchorTextColor: '#334155',
    anchorTextHoverColor: '#1e293b',
    dividerBackground: '#e2e8f0',
    messageText: '#0a0a0a',
    messageTextDanger: '#ef4444',
  },
  fonts: {
    bodyFontFamily: 'var(--font-inter), Inter, sans-serif',
    buttonFontFamily: 'var(--font-inter), Inter, sans-serif',
    inputFontFamily: 'var(--font-inter), Inter, sans-serif',
    labelFontFamily: 'var(--font-inter), Inter, sans-serif',
  },
  fontSizes: {
    baseInputSize: '14px',
    baseLabelSize: '14px',
    baseBodySize: '14px',
    baseButtonSize: '14px',
  },
  borderWidths: {
    buttonBorderWidth: '1px',
    inputBorderWidth: '1px',
  },
  radii: {
    borderRadiusButton: '0.5rem',
    buttonBorderRadius: '0.5rem',
    inputBorderRadius: '0.5rem',
  },
  space: {
    inputPadding: '0.625rem 0.75rem',
    buttonPadding: '0.625rem 1rem',
  },
}

export const authVariablesDark = {
  colors: {
    brand: '#334155',
    brandAccent: '#475569',
    brandButtonText: '#ffffff',
    inputBackground: '#222222',
    inputBorder: '#2a2a2a',
    inputBorderHover: '#3a3a3a',
    inputBorderFocus: '#475569',
    inputText: '#ffffff',
    inputLabelText: '#e7e5e5',
    inputPlaceholder: '#9f9d9d',
    defaultButtonBackground: '#222222',
    defaultButtonBackgroundHover: '#2a2a2a',
    defaultButtonBorder: '#2a2a2a',
    defaultButtonText: '#e7e5e5',
    anchorTextColor: '#9f9d9d',
    anchorTextHoverColor: '#e7e5e5',
    dividerBackground: '#2a2a2a',
    messageText: '#ffffff',
    messageTextDanger: '#ee7d77',
  },
  fonts: {
    bodyFontFamily: 'var(--font-inter), Inter, sans-serif',
    buttonFontFamily: 'var(--font-inter), Inter, sans-serif',
    inputFontFamily: 'var(--font-inter), Inter, sans-serif',
    labelFontFamily: 'var(--font-inter), Inter, sans-serif',
  },
  fontSizes: {
    baseInputSize: '14px',
    baseLabelSize: '14px',
    baseBodySize: '14px',
    baseButtonSize: '14px',
  },
  borderWidths: {
    buttonBorderWidth: '1px',
    inputBorderWidth: '1px',
  },
  radii: {
    borderRadiusButton: '0.5rem',
    buttonBorderRadius: '0.5rem',
    inputBorderRadius: '0.5rem',
  },
  space: {
    inputPadding: '0.625rem 0.75rem',
    buttonPadding: '0.625rem 1rem',
  },
}
